export const RACING_GAME = Object.freeze({
    CAR_NAME_SEPARATOR: ',',
    RANDOM_MIN: 0,
    RANDOM_MAX: 9,
    FORWARD_THRESHOLD: 3,
    FORWARD_DISTANCE: 1,
    MIN_CAR_LENGTH: 2,
    MAX_CAR_NAME_LENGTH: 5,
    LIMIT_ROUND_COUNT: 100,
});
